import tseslint from 'typescript-eslint';

// Minimal, fast (non-type-checked) lint across all workspaces.
// eslint-config-next joins at A2, when real React code lands in apps/web.
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/coverage/**',
      'packages/db/src/generated/**',
      // Generated by `next build`, and it says so in its own header. Next 15
      // adds a `path` triple-slash reference, which the recommended rules
      // reject -- but the file is not ours to edit.
      '**/next-env.d.ts',
      'docs/**',
    ],
  },
  ...tseslint.configs.recommended,
);
