/**
 * Snapshots Affinity's dropdown vocabularies to a committed JSON file.
 *
 *   npm run affinity:vocab
 *
 * ADR-009 requires the funnel to be seeded from Affinity's field METADATA
 * rather than from observed values, because options exist in the configuration
 * that no row has ever used. That endpoint is live, so the obvious move would
 * be to have `db:seed` call it directly. It deliberately does not:
 *
 *   - `db:seed` must run offline. CI's database job seeds a throwaway Postgres
 *     with no Affinity key, and a seed that needs the network is a seed that
 *     fails for reasons unrelated to the schema.
 *   - Seeding must be deterministic. Two developers seeding on different days
 *     would otherwise get different reference tables, and the idempotency
 *     assertion in CI would be checking nothing.
 *
 * So the snapshot is committed and `db:seed` reads the file. Refreshing the
 * vocabulary is this command plus a commit, which keeps the change reviewable.
 * The nightly sync separately upserts newly-seen options at run time, so a
 * dropdown added on a Tuesday does not need a deploy (ADR-009).
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from 'dotenv';

import { createAffinityClient, NBIF_MASTER_LIST_ID, type DropdownOption, type FieldMeta } from './client.js';

/**
 * The fields whose vocabularies the platform actually consumes. Deliberately
 * a short list rather than every dropdown on the list: Pass Reason and
 * Product/Service Industry are stored verbatim and need no reference table,
 * and the scoring fields are unused.
 */
export const VOCABULARY_FIELDS = {
  status: 'Status',                       // -> affinity_status_map keys
  prioritySector: 'Priority Sector',      // -> ref_sector
  sourceOfDeal: 'Source of Deal',         // -> ref_source_channel
  riskAssessment: 'Risk Assessment',      // CHECK constraint; snapshotted to catch drift
  portfolioStatus: 'Portfolio Status',    // company_state.lifecycle_status
  nbRegion: 'New Brunswick Region',       // CHECK constraint; same
} as const;

export interface VocabularySnapshot {
  generatedAt: string;
  listId: number;
  note: string;
  fields: Record<
    string,
    { fieldId: string; valueType: string; options: DropdownOption[] }
  >;
}

const here = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(here, '../../..');
export const SNAPSHOT_PATH = path.resolve(REPO_ROOT, 'docs/affinity-vocabularies-v2.json');

async function main(): Promise<void> {
  config({ path: path.resolve(REPO_ROOT, '.env') });
  config();

  const apiKey = process.env.AFFINITY_API_KEY;
  if (!apiKey) {
    console.error('AFFINITY_API_KEY is not set. See .env.example.');
    process.exit(1);
  }

  const af = createAffinityClient(apiKey);
  const fields = await af.collect<FieldMeta>(`/lists/${NBIF_MASTER_LIST_ID}/fields`);

  const snapshot: VocabularySnapshot = {
    generatedAt: new Date().toISOString(),
    listId: NBIF_MASTER_LIST_ID,
    note:
      'Generated by `npm run affinity:vocab`. Do not hand-edit -- correct the option in ' +
      'Affinity, which is system of record (ADR-009), and regenerate. Read by packages/db seed.',
    fields: {},
  };

  for (const [key, name] of Object.entries(VOCABULARY_FIELDS)) {
    const field = fields.find((f) => f.name === name);
    if (!field) {
      console.error(`Field "${name}" not found on list ${NBIF_MASTER_LIST_ID}.`);
      process.exit(1);
    }
    const options = await af.collect<DropdownOption>(
      `/lists/${NBIF_MASTER_LIST_ID}/fields/${field.id}/dropdown-options`,
    );
    // rank is carried only by ranked-dropdown; sort those, leave the rest as
    // Affinity returns them so the file is stable between runs.
    const ranked = options.every((o) => typeof o.rank === 'number');
    snapshot.fields[key] = {
      fieldId: field.id,
      valueType: field.valueType,
      options: ranked ? [...options].sort((a, b) => a.rank - b.rank) : options,
    };
    console.log(`${name.padEnd(24)} ${field.id.padEnd(18)} ${options.length} options`);
  }

  writeFileSync(SNAPSHOT_PATH, JSON.stringify(snapshot, null, 2) + '\n');
  console.log(`\nwrote ${path.relative(process.cwd(), SNAPSHOT_PATH)} in ${af.calls} calls`);
}

await main();
